/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as GetAccessRouteImport } from './routes/get-access'
import { Route as ForensicsPillarsRouteImport } from './routes/forensics-pillars'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAccessRoute = GetAccessRouteImport.update({
  id: '/get-access',
  path: '/get-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsPillarsRoute = ForensicsPillarsRouteImport.update({
  id: '/forensics-pillars',
  path: '/forensics-pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/forensics-pillars': typeof ForensicsPillarsRoute
  '/get-access': typeof GetAccessRoute
  '/offerings': typeof OfferingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/forensics-pillars': typeof ForensicsPillarsRoute
  '/get-access': typeof GetAccessRoute
  '/offerings': typeof OfferingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/forensics-pillars': typeof ForensicsPillarsRoute
  '/get-access': typeof GetAccessRoute
  '/offerings': typeof OfferingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/contact'
    | '/forensics-pillars'
    | '/get-access'
    | '/offerings'
    | '/blog/$slug'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/contact'
    | '/forensics-pillars'
    | '/get-access'
    | '/offerings'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/contact'
    | '/forensics-pillars'
    | '/get-access'
    | '/offerings'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  ForensicsPillarsRoute: typeof ForensicsPillarsRoute
  GetAccessRoute: typeof GetAccessRoute
  OfferingsRoute: typeof OfferingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-access': {
      id: '/get-access'
      path: '/get-access'
      fullPath: '/get-access'
      preLoaderRoute: typeof GetAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics-pillars': {
      id: '/forensics-pillars'
      path: '/forensics-pillars'
      fullPath: '/forensics-pillars'
      preLoaderRoute: typeof ForensicsPillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  ForensicsPillarsRoute: ForensicsPillarsRoute,
  GetAccessRoute: GetAccessRoute,
  OfferingsRoute: OfferingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
